
name: Update the blogs
on:
  push:
    branches:
      - master
  schedule:
    # runs every hour
    - cron: '0 * * * *'
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch newest blog post and put in README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://galenwong.github.io/rss.xml"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Write MyMix to README
        env:
          TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        run: |
          python write_youtube_mymix.py
      - name: Commit and push
        run: |
          git diff
          git config --global user.email "wonggalen1999@gmail.com"
          git config --global user.name "mymix-bot"
          git pull 
          git add -A 
          git commit -m "Update YouTube Mymix" || exit 0
          git push
      